name: Django CI

on:
  push:
    branches:
      - main
  workflow_dispatch: # manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r meme_gen/requirements.txt

    - name: Run Tests
      run: |
        cd meme_gen
        python manage.py test